const CONFIG = {
    introTitle: 'Minh Chơn à!',
    introDesc: ` Em pé cho anh xem cái này nè`,
    btnIntro: 'uki em pé',
    title: 'Anh có muốn làm chồng em pé hongggggg :>>',
    desc: 'Nếu có thì ấn vào dòng màu xanh iiii ',
    btnYes: ' Anh cóoo ',
    btnNo: 'Anh muốn làm chồng péee',
    question:' Nói em biết lí do sao anh muốn làm chồng em iii <3',
    btnReply: ' Gửi cho em pé <3',
    reply: 'Tại em pé dễ thương đáng iu tốt bụng',
    mess: ' Em biết mà:>. Yêu anh nhiều nhiều',
    messDesc: 'Tối nay 9h anh có muốn coi phim với em honggg.',
    btnAccept: 'Có chứ',
   
